---
- hosts: awx
  tasks:
   - name: Install dependeces AWX
     yum: name={{item}} state=present disable_gpg_check=yes
     with_items:
      - epel-release
      - git
      - gettext
      - ansible
      - docker
      - nodejs
      - npm
      - gcc-c++
      - bzip2
      - python-docker-py

   - name: Enable docker to be started at boot
     service: name=docker.service enabled=yes state=started

   - name: Enable docker to be started at boot
     service: name=docker.service enabled=yes state=started

   - name: Firewall settings 80
     firewalld: zone=public port=80/tcp permanent=true state=enabled
  
   - name: FIX postgres_data_dir
     file: path=/root/pgdocker state=directory
